{% set name = "universal_pathlib" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # If getting the source from GitHub, remove the line above,
  # uncomment the line below, and modify as needed. Use releases if available:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6bc215548792ad5db3553708b1c19bafd9e2fa1667dc925ed404c95e52ae2f13

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools-scm
  run:
    - python >=3.8
    - fsspec >=2022.1.0


test:
  imports:
    - upath

about:
  home: https://github.com/Quansight/universal_pathlib
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: pathlib api extended to use fsspec backends
  dev_url: https://github.com/Quansight/universal_pathlib

extra:
  recipe-maintainers:
    - ap--
    - andrewfulton9
