{% set name = "universal_pathlib" %}
{% set version = "0.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # If getting the source from GitHub, remove the line above,
  # uncomment the line below, and modify as needed. Use releases if available:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 22f5f289fedec4b663956596742652e2177bca24661b6c8a173f5974cfee0052

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools >=48
    - setuptools-scm >=6.3.1
  run:
    - python >=3.8
    - fsspec >=2022.1.0


test:
  imports:
    - upath

about:
  home: https://github.com/fsspec/universal_pathlib
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: pathlib api extended to use fsspec backends
  dev_url: https://github.com/fsspec/universal_pathlib

extra:
  recipe-maintainers:
    - ap--
    - andrewfulton9
