{% set name = "universal_pathlib" %}
{% set version = "0.0.24" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # If getting the source from GitHub, remove the line above,
  # uncomment the line below, and modify as needed. Use releases if available:
  # url: https://github.com/Quansight/universal_pathlib/releases/download/{{ version }}/universal_pathlib-{{ version }}.tar.gz
  url: https://github.com/Quansight/universal_pathlib/archive/v{{ version }}.tar.gz
  sha256: f1c5d8dfe7a1311ac0c117d945eefd12a6ea8a12ea61666a08a02cbf63599921

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools-scm
  run:
    - python >=3.8
    - fsspec


test:
  imports:
    - upath

about:
  home: https://github.com/Quansight/universal_pathlib
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: pathlib api extended to use fsspec backends
  dev_url: https://github.com/Quansight/universal_pathlib

extra:
  recipe-maintainers:
    - ap--
    - andrewfulton9
